version: "3.8"
services:
  immutable:
    build: .
    restart: always
    volumes:
      - .:/src
    ports:
      - 8080:8080
  
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  